### PR TITLE
Full refresh of state yml

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Why does it remove packages? E.g. ABSurvTDC right at the beginning?

**Comment by jeroen** [comment]
Because that repo does not exist on https://github.com/cran/ABSurvTDC

**Comment by gaborcsardi** [comment]
Hmmm, but these should be in the file as well, otherwise they are not added. Essentially everything from metacran should be in the file. So if something is already there, we should not delete it.

**Comment by jeroen** [comment]
So what version should be in the yml if it is not actually on the mirror? How do we trigger the build system to actually create the mirror repo?

**Comment by gaborcsardi** [comment]
Actually, you are right, and it should not be there.

**Comment by gaborcsardi** [comment]
All good then, let me merge and trigger a build. I guess a couple of packages will fail to update, we'll see.

**Pull request merged**
